version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - default
    
      - backend
    environment:
      GREET_NAME: CWiCS BOOST attendees
    expose:
      - 8080

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.multistage
    networks:
      - backend
    ports:
      - 8081:8080

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8082:80

networks:
  backend:
